{% set name = "VIBRANT" %}
{% set  version = "1.1.0" %}
{% set sha256 = "e3185c4f3a73889230a31be7c32a1bd2f390036836bc3a773575afa747ec0088" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/AnantharamanLab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - path.patch

build:
  number: 0
  noarch: generic

requirements:
  host:
    - wget
  run:
    - python >=3.5
    - prodigal
    - hmmer
    - biopython
    - pandas
    - matplotlib-base
    - seaborn
    - numpy >=1.17.0
    - scikit-learn <=0.21.3
    - wget

test:
  commands:
    - VIBRANT_run.py -h
    - VIBRANT_annotation.py -h

about:
  home: https://github.com/AnantharamanLab/VIBRANT
  license: GPL
  license_family: GPL
  license_file: LICENSE
  summary: "Virus Identification By iteRative ANnoTation"

extra:
  identifiers:
    - doi:10.1101/855387
  notes: "Read post-link.sh on how to download 11GB required data files."
