{% set name = "crisprbact" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d9e91eaa4a437da53a2efa7e3ebc242e7d9c66fb8b555335ba88e66925349446

build:
  number: 0
  noarch: python
  entry_points:
    - crisprbact = crisprbact.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - biopython >=1.75,<2.0
    - click >=7.0,<8.0
    - numpy >=1.17,<2.0
    - pip
    - python >=3.5
    - poetry >=1.0.0
  run:
    - biopython >=1.75,<2.0
    - click >=7.0,<8.0
    - numpy >=1.17,<2.0
    - python >=3.5

test:
  imports:
    - crisprbact
  commands:
    - crisprbact --help

about:
  home: "https://gitlab.pasteur.fr/dbikard/crisprbact"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: "Tools to design and analyse CRISPRi experiments"

extra:
  recipe-maintainers:
    - rplanel
