{% set version = '1.3' %}

package:
  name: r-phylosignal
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/phylosignal_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/phylosignal/phylosignal_{{ version }}.tar.gz
  sha256: a563bedf4ed8f81b9d3b64f45ab6eb0e64572b35012f5f13da652afe19e7e3c0

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - r-base
    - r-dbi
    - r-rcpp >=0.11.0
    - r-rcpparmadillo
    - r-adephylo
    - r-ape
    - r-boot
    - r-igraph
    - r-phylobase
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-dbi
    - r-rcpp >=0.11.0
    - r-rcpparmadillo
    - r-adephylo
    - r-ape
    - r-boot
    - r-igraph
    - r-phylobase

test:
  commands:

    - $R -e "library('phylosignal')"           # [not win]
    - "\"%R%\" -e \"library('phylosignal')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=phylosignal
  license: GPL-3
  summary: A collection of tools to explore the phylogenetic signal in univariate and multivariate
    data. The package provides functions to plot traits data against a phylogenetic
    tree, different measures and tests for the phylogenetic signal, methods to describe
    where the signal is located and a phylogenetic clustering method.
  license_family: GPL3

extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
